import Mathlib.Data.Real.Basic

/-!
# Abstract vocabulary for the focused implication

This file deliberately does not model hyperbolic surfaces or number fields.
It records only the types, numerical invariants, and predicates used in the
manuscript's final deduction.  The analytic, geometric, and arithmetic
statements used by that deduction are hypotheses in `ExternalInputs.lean`.
-/

namespace TraceSparsity

/-- The data used by the final local-to-global argument for one compact
hyperbolic surface. -/
structure CompactTraceDatum where
  /-- Faithful cocompact Fuchsian characters in the selected real
  neighborhood under consideration.  The abstract model does not construct
  this space; algebraicity and persistence in the rational closure are
  recorded by separate predicates below. -/
  Character : Type
  /-- Elements of the lifted subgroup generated by squares. -/
  Element : Type
  /-- The original Fuchsian character. -/
  distinguished : Character
  /-- Translation length at the original character. -/
  length : Element → ℝ
  /-- The sum of local expanding contributions at an algebraic character. -/
  localHeight : Character → Element → ℝ
  /-- Algebraicity of a character. -/
  IsAlgebraic : Character → Prop
  /-- Persistence of all squared-trace collisions from the original point. -/
  IsPersistent : Character → Prop
  /-- Central elements are handled separately in the local theorem. -/
  IsCentral : Element → Prop
  /-- The condition `b ≠ 1`; it is used for the distinguished-place lower
  bound on the local height. -/
  IsNonidentity : Element → Prop
  /-- The critical trace-counting hypothesis used by the local-expansion
  argument: in the strengthened manuscript this is upper polynomial
  trace-counting exponent at most one.  It is kept distinct from literal
  linear growth so the formal statement records the strengthening. -/
  CriticalTraceGrowth : Prop
  /-- Literal linear growth of the signed trace set, the hypothesis in the
  original formulation of the compact Schmutz conjecture. -/
  LinearTraceGrowth : Prop
  /-- Uniform bounded clustering of the signed trace set. -/
  BoundedClustering : Prop
  /-- Integrality of all traces in the subgroup generated by squares. -/
  IntegralTraces : Prop
  /-- Boundedness at every nondistinguished real embedding. -/
  BoundedNondistinguishedConjugates : Prop
  /-- Total reality of the full trace field of the subgroup generated by
  squares. -/
  TotallyRealTraceField : Prop
  /-- Arithmeticity of the subgroup generated by squares, the direct output
  of Takeuchi's criterion. -/
  SquareSubgroupArithmetic : Prop
  /-- The subgroup generated by squares has finite covolume.  This premise is
  explicit because it is essential in the finite-covolume form of Takeuchi's
  criterion used by the manuscript. -/
  SquareSubgroupFiniteCovolume : Prop
  /-- The subgroup generated by squares has finite index in the original
  lattice. -/
  SquareSubgroupFiniteIndex : Prop
  /-- Arithmeticity of the original cocompact Fuchsian group. -/
  Arithmetic : Prop

namespace CompactTraceDatum

/-- An algebraic point of the rational closure at which collision identities
from the distinguished character persist. -/
def Eligible (D : CompactTraceDatum) (y : D.Character) : Prop :=
  D.IsAlgebraic y ∧ D.IsPersistent y

/-- The pointwise conclusion of the persistent local-expansion theorem. -/
def LocalExpansionAt (D : CompactTraceDatum) (y : D.Character) : Prop :=
  ∀ b : D.Element, D.localHeight y b ≤ D.length b / 2

/-- The full conclusion of the persistent local-expansion theorem. -/
def PersistentLocalExpansion (D : CompactTraceDatum) : Prop :=
  ∀ y : D.Character, D.Eligible y → D.LocalExpansionAt y

end CompactTraceDatum

end TraceSparsity
