import Mathlib.Algebra.Order.Chebyshev
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.LinearCombination

/-!
# Algebraic and finite-counting core of the congruence-wedge argument

The first two results below formalize the elementary Chinese-remainder
confinement used for the wedge map

`(u,v,u') ↦ (Q*u - P*v, Q*v - P*u')`.

They show directly, over any commutative ring, that equal wedge images force
the middle coordinates to agree modulo `P*Q` whenever a Bezout relation for
`P,Q` is supplied.  Over an integral domain, a wedge image together with its
middle coordinate determines the entire triple when `P,Q` are nonzero.

The remaining results formalize the finite counting after that algebraic
step: a map with fibers of size at most `M` cannot have a source larger than
`M * |X| * |Y|`, and Cauchy--Schwarz turns the sum of squared degrees into
the square of the edge count.
-/

namespace TraceSparsity

/-- An ordered length-two path, recorded only through its two endpoints and
common middle trace value. -/
structure WedgeTriple (R : Type*) where
  left : R
  middle : R
  right : R
  deriving DecidableEq

/-- The pair of recurrence projections attached to an ordered length-two
path. -/
def wedgeImage {R : Type*} [CommRing R] (P Q : R)
    (w : WedgeTriple R) : R × R :=
  (Q * w.left - P * w.middle, Q * w.middle - P * w.right)

/-- The elements of a finite set lying in the principal congruence class of
`c` modulo `P * Q`.  This noncomputable definition uses classical
decidability only to filter a finite set; the mathematical predicate is the
displayed divisibility relation. -/
noncomputable def principalResidueClass
    {R : Type*} [CommRing R] (P Q : R) (values : Finset R) (c : R) :
    Finset R := by
  classical
  exact values.filter fun v => ∃ r : R, v - c = (P * Q) * r

theorem mem_principalResidueClass
    {R : Type*} [CommRing R] (P Q : R) (values : Finset R) (c v : R) :
    v ∈ principalResidueClass P Q values c ↔
      v ∈ values ∧ ∃ r : R, v - c = (P * Q) * r := by
  classical
  simp [principalResidueClass]

/-- Equal images under the two-coordinate wedge map confine the difference
of the middle coordinates to the principal ideal generated by `P * Q`.

The hypothesis `a * P + b * Q = 1` is the explicit Bezout form of the
coprimality condition `(P) + (Q) = R`.  This is the algebraic
Chinese-remainder step in the manuscript; no Dedekind-domain machinery is
needed for this direction. -/
theorem wedge_middle_congruent
    {R : Type*} [CommRing R]
    (P Q a b : R) (hbezout : a * P + b * Q = 1)
    {u v u' u₁ v₁ u₁' : R}
    (hminus : Q * u - P * v = Q * u₁ - P * v₁)
    (hplus : Q * v - P * u' = Q * v₁ - P * u₁') :
    ∃ r : R, v - v₁ = (P * Q) * r := by
  have hx : P * (v - v₁) = Q * (u - u₁) := by
    linear_combination -hminus
  have hz : Q * (v - v₁) = P * (u' - u₁') := by
    linear_combination hplus
  have hQ : v - v₁ = Q * (a * (u - u₁) + b * (v - v₁)) := by
    calc
      v - v₁ = (a * P + b * Q) * (v - v₁) := by rw [hbezout, one_mul]
      _ = a * (P * (v - v₁)) + b * Q * (v - v₁) := by ring
      _ = a * (Q * (u - u₁)) + b * Q * (v - v₁) := by rw [hx]
      _ = Q * (a * (u - u₁) + b * (v - v₁)) := by ring
  have hP : v - v₁ = P * (a * (v - v₁) + b * (u' - u₁')) := by
    calc
      v - v₁ = (a * P + b * Q) * (v - v₁) := by rw [hbezout, one_mul]
      _ = a * P * (v - v₁) + b * (Q * (v - v₁)) := by ring
      _ = a * P * (v - v₁) + b * (P * (u' - u₁')) := by rw [hz]
      _ = P * (a * (v - v₁) + b * (u' - u₁')) := by ring
  let rQ : R := a * (u - u₁) + b * (v - v₁)
  let rP : R := a * (v - v₁) + b * (u' - u₁')
  have hrQ : rQ = P * (a * rQ + b * rP) := by
    calc
      rQ = (a * P + b * Q) * rQ := by rw [hbezout, one_mul]
      _ = a * P * rQ + b * (Q * rQ) := by ring
      _ = a * P * rQ + b * (v - v₁) := by rw [hQ]
      _ = a * P * rQ + b * (P * rP) := by rw [hP]
      _ = P * (a * rQ + b * rP) := by ring
  refine ⟨a * rQ + b * rP, ?_⟩
  calc
    v - v₁ = Q * rQ := hQ
    _ = Q * (P * (a * rQ + b * rP)) :=
      congrArg (fun t : R => Q * t) hrQ
    _ = (P * Q) * (a * rQ + b * rP) := by ring

/-- Over an integral domain, an image under the wedge map and its middle
coordinate determine the two remaining coordinates.  Together with
`wedge_middle_congruent`, this is the injectivity statement used to bound a
wedge fiber by the population of one residue class modulo `P * Q`. -/
theorem wedge_triple_eq_of_same_middle
    {R : Type*} [CommRing R] [IsDomain R]
    (P Q : R) (hP : P ≠ 0) (hQ : Q ≠ 0)
    {u v u' u₁ v₁ u₁' : R}
    (hv : v = v₁)
    (hminus : Q * u - P * v = Q * u₁ - P * v₁)
    (hplus : Q * v - P * u' = Q * v₁ - P * u₁') :
    u = u₁ ∧ v = v₁ ∧ u' = u₁' := by
  subst v₁
  constructor
  · apply mul_left_cancel₀ hQ
    linear_combination hminus
  · refine ⟨rfl, ?_⟩
    apply mul_left_cancel₀ hP
    linear_combination -hplus

/-- A fully algebraic version of the wedge-fiber estimate.  The only
remaining counting hypothesis is the manuscript's definition of `M`: every
congruence class modulo the principal element `P * Q` contains at most `M`
members of the finite middle-coordinate set.

The proof selects one triple in a nonempty wedge fiber.  Chinese-remainder
confinement puts every other middle coordinate in its residue class, while
`wedge_triple_eq_of_same_middle` makes projection to the middle coordinate
injective on that fiber. -/
theorem wedge_fiber_card_le_congruence_class
    {R : Type*} [CommRing R] [IsDomain R] [DecidableEq R]
    (P Q a b : R) (hP : P ≠ 0) (hQ : Q ≠ 0)
    (hbezout : a * P + b * Q = 1)
    (wedges : Finset (WedgeTriple R)) (middles : Finset R) (M : ℕ)
    (middle_mem : ∀ w ∈ wedges, w.middle ∈ middles)
    (residueClass : R → Finset R)
    (residueClass_spec : ∀ c v, v ∈ residueClass c ↔
      v ∈ middles ∧ ∃ r : R, v - c = (P * Q) * r)
    (classBound : ∀ c : R, (residueClass c).card ≤ M)
    (image : R × R) :
    (wedges.filter fun w => wedgeImage P Q w = image).card ≤ M := by
  classical
  let fiber := wedges.filter fun w => wedgeImage P Q w = image
  by_cases hEmpty : fiber = ∅
  · simp [fiber, hEmpty]
  · obtain ⟨w₀, hw₀⟩ := Finset.nonempty_iff_ne_empty.mpr hEmpty
    have hMaps : Set.MapsTo (fun w : WedgeTriple R => w.middle)
        (fiber : Set (WedgeTriple R)) (residueClass w₀.middle : Set R) := by
      intro w hw
      have hw' : w ∈ wedges ∧ wedgeImage P Q w = image := by
        simpa [fiber] using hw
      have hw₀' : w₀ ∈ wedges ∧ wedgeImage P Q w₀ = image := by
        simpa [fiber] using hw₀
      have hsame : wedgeImage P Q w = wedgeImage P Q w₀ :=
        hw'.2.trans hw₀'.2.symm
      have hcongruent : ∃ r : R,
          w.middle - w₀.middle = (P * Q) * r :=
        wedge_middle_congruent P Q a b hbezout
          (congrArg Prod.fst hsame) (congrArg Prod.snd hsame)
      exact (residueClass_spec w₀.middle w.middle).2
        ⟨middle_mem w hw'.1, hcongruent⟩
    have hInj : ((fiber : Set (WedgeTriple R))).InjOn
        (fun w : WedgeTriple R => w.middle) := by
      intro w₁ hw₁ w₂ hw₂ hmiddle
      have hw₁' : w₁ ∈ wedges ∧ wedgeImage P Q w₁ = image := by
        simpa [fiber] using hw₁
      have hw₂' : w₂ ∈ wedges ∧ wedgeImage P Q w₂ = image := by
        simpa [fiber] using hw₂
      have hsame : wedgeImage P Q w₁ = wedgeImage P Q w₂ :=
        hw₁'.2.trans hw₂'.2.symm
      obtain ⟨hleft, _, hright⟩ :=
        wedge_triple_eq_of_same_middle P Q hP hQ hmiddle
          (congrArg Prod.fst hsame) (congrArg Prod.snd hsame)
      cases w₁
      cases w₂
      simp_all
    calc
      fiber.card ≤ (residueClass w₀.middle).card :=
        Finset.card_le_card_of_injOn _ hMaps hInj
      _ ≤ M := classBound w₀.middle

/-- Specialization of `wedge_fiber_card_le_congruence_class` in which the
residue classes are the literal finite filters defined by
`principalResidueClass`. -/
theorem wedge_fiber_card_le_principal_residue_class
    {R : Type*} [CommRing R] [IsDomain R] [DecidableEq R]
    (P Q a b : R) (hP : P ≠ 0) (hQ : Q ≠ 0)
    (hbezout : a * P + b * Q = 1)
    (wedges : Finset (WedgeTriple R)) (middles : Finset R) (M : ℕ)
    (middle_mem : ∀ w ∈ wedges, w.middle ∈ middles)
    (classBound : ∀ c : R,
      (principalResidueClass P Q middles c).card ≤ M)
    (image : R × R) :
    (wedges.filter fun w => wedgeImage P Q w = image).card ≤ M := by
  exact wedge_fiber_card_le_congruence_class
    P Q a b hP hQ hbezout wedges middles M middle_mem
    (principalResidueClass P Q middles)
    (mem_principalResidueClass P Q middles) classBound image

/-- Abstract finite-fiber counting, applied in the manuscript to the wedge
map `(u,v,u') ↦ (Qu-Pv,Qv-Pu')`. -/
theorem card_le_fiberBound_mul_product
    {W X Y : Type*} [DecidableEq W] [DecidableEq X] [DecidableEq Y]
    (wedges : Finset W) (left : Finset X) (right : Finset Y)
    (f : W → X × Y) (M : ℕ)
    (mapsTo : ∀ w ∈ wedges, f w ∈ left.product right)
    (fiberBound : ∀ p ∈ left.product right,
      (wedges.filter fun w => f w = p).card ≤ M) :
    wedges.card ≤ M * (left.card * right.card) := by
  have h := Finset.card_le_mul_card_image_of_maps_to mapsTo M fiberBound
  simpa [Finset.card_product, Nat.mul_assoc] using h

/-- Cauchy--Schwarz in the precise form used for the degrees on the second
vertex class of a bipartite graph. -/
theorem square_sum_degrees_le
    {V : Type*} [DecidableEq V]
    (vertices : Finset V) (degree : V → ℕ) :
    (∑ v ∈ vertices, (Nat.cast (degree v) : ℝ)) ^ 2 ≤
      (Nat.cast vertices.card : ℝ) *
        ∑ v ∈ vertices, (Nat.cast (degree v) : ℝ) ^ 2 := by
  exact sq_sum_le_card_mul_sum_sq

/-- Denominator-free form of the complete abstract wedge bound.  If the
number of wedges is the sum of squared degrees and every fiber of the wedge
map has size at most `M`, then

`|E|² ≤ |V| M |X₋| |X₊|`.

Here `|E|` is written as the sum of the degrees, so no separate edge type is
needed. -/
theorem abstract_congruence_wedge_bound
    {W X Y V : Type*}
    [DecidableEq W] [DecidableEq X] [DecidableEq Y] [DecidableEq V]
    (wedges : Finset W) (left : Finset X) (right : Finset Y)
    (vertices : Finset V) (degree : V → ℕ)
    (f : W → X × Y) (M : ℕ)
    (wedgeCount : wedges.card = ∑ v ∈ vertices, (degree v) ^ 2)
    (mapsTo : ∀ w ∈ wedges, f w ∈ left.product right)
    (fiberBound : ∀ p ∈ left.product right,
      (wedges.filter fun w => f w = p).card ≤ M) :
    (∑ v ∈ vertices, (Nat.cast (degree v) : ℝ)) ^ 2 ≤
      (Nat.cast vertices.card : ℝ) * (Nat.cast M : ℝ) *
        (Nat.cast left.card : ℝ) * (Nat.cast right.card : ℝ) := by
  have hfinite := card_le_fiberBound_mul_product
    wedges left right f M mapsTo fiberBound
  have hfiniteReal : (Nat.cast wedges.card : ℝ) ≤
      (Nat.cast (M * (left.card * right.card)) : ℝ) := by
    exact_mod_cast hfinite
  have hwedgeReal :
      (∑ v ∈ vertices, (Nat.cast (degree v) : ℝ) ^ 2) =
        (Nat.cast wedges.card : ℝ) := by
    rw [wedgeCount]
    simp only [Nat.cast_sum, Nat.cast_pow]
  calc
    (∑ v ∈ vertices, (Nat.cast (degree v) : ℝ)) ^ 2 ≤
        (Nat.cast vertices.card : ℝ) *
          ∑ v ∈ vertices, (Nat.cast (degree v) : ℝ) ^ 2 :=
      square_sum_degrees_le vertices degree
    _ = (Nat.cast vertices.card : ℝ) * (Nat.cast wedges.card : ℝ) := by
      rw [hwedgeReal]
    _ ≤ (Nat.cast vertices.card : ℝ) *
        (Nat.cast (M * (left.card * right.card)) : ℝ) := by
      exact mul_le_mul_of_nonneg_left hfiniteReal (Nat.cast_nonneg _)
    _ = (Nat.cast vertices.card : ℝ) * (Nat.cast M : ℝ) *
        (Nat.cast left.card : ℝ) * (Nat.cast right.card : ℝ) := by
      norm_cast
      ring

/-- The congruence-wedge inequality with its fiber bound proved by the
explicit Bezout/CRT argument above.  Its only remaining arithmetic counting
hypothesis is the bound `M` on the number of allowed middle values in one
residue class modulo `P * Q`.

This theorem is deliberately stated for a commutative integral domain rather
than a Dedekind domain: unique factorization of ideals is not used in the
congruence-wedge lemma itself. -/
theorem congruence_wedge_bound_from_residue_classes
    {R V : Type*}
    [CommRing R] [IsDomain R] [DecidableEq R] [DecidableEq V]
    (P Q a b : R) (hP : P ≠ 0) (hQ : Q ≠ 0)
    (hbezout : a * P + b * Q = 1)
    (wedges : Finset (WedgeTriple R))
    (middles left right : Finset R)
    (vertices : Finset V) (degree : V → ℕ) (M : ℕ)
    (middle_mem : ∀ w ∈ wedges, w.middle ∈ middles)
    (classBound : ∀ c : R,
      (principalResidueClass P Q middles c).card ≤ M)
    (wedgeCount : wedges.card = ∑ v ∈ vertices, (degree v) ^ 2)
    (mapsTo : ∀ w ∈ wedges, wedgeImage P Q w ∈ left.product right) :
    (∑ v ∈ vertices, (Nat.cast (degree v) : ℝ)) ^ 2 ≤
      (Nat.cast vertices.card : ℝ) * (Nat.cast M : ℝ) *
        (Nat.cast left.card : ℝ) * (Nat.cast right.card : ℝ) := by
  apply abstract_congruence_wedge_bound
    wedges left right vertices degree (wedgeImage P Q) M wedgeCount mapsTo
  intro image _
  exact wedge_fiber_card_le_principal_residue_class
    P Q a b hP hQ hbezout wedges middles M middle_mem
    classBound image

end TraceSparsity
